# Generated by Django 2.2 on 2022-08-15 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(default='Exercise Name', max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='number_of_reps_per_set',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='number_of_sets',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight_per_rep',
            field=models.IntegerField(default=15),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField()),
                ('workout_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', related_name='exercise', to='tracker.Workout'),
        ),
    ]
