# Generated by Django 2.2 on 2022-08-15 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20220815_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date_of_workout',
            field=models.DateField(default=datetime.datetime(2022, 8, 15, 16, 46, 28, 32301)),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='time_of_workout',
            field=models.TimeField(default=datetime.time(16, 46, 28, 32301)),
        ),
    ]
