# Generated by Django 2.2 on 2022-08-16 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20220815_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='date_of_workout',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='time_of_workout',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(default='Enter Exercise Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='number_of_reps_per_set',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='number_of_sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight_per_rep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 12, 4, 52, 105390)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_time',
            field=models.TimeField(default=datetime.time(12, 4, 52, 106390)),
        ),
    ]
