# Generated by Django 2.2 on 2022-08-16 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20220816_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 15, 24, 14, 555705)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_time',
            field=models.TimeField(default=datetime.time(15, 24, 14, 555705)),
        ),
    ]
