# Generated by Django 2.2 on 2022-08-18 12:03

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20220818_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 18, 8, 3, 14, 385789)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_time',
            field=models.TimeField(default=datetime.time(8, 3, 14, 385789)),
        ),
    ]
