# Generated by Django 2.2 on 2022-08-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20220826_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='number_of_reps_per_set',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='number_of_sets',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight_per_rep',
            field=models.IntegerField(),
        ),
    ]
